services:
  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: unless-stopped

  todo-app:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_BASE_PATH=${NEXT_PUBLIC_BACKEND_BASE_PATH}
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
    restart: unless-stopped
