version: '3.8'
services:
  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    env_file:
      - backend.env
    ports:
      - "3001:3001"
    restart: unless-stopped

  todo-app:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
    restart: unless-stopped